# Slack API token
token:
  xoxb-284880722629-u0xNUs4xcWuzajkW21RCNE65

# Bot configuration
bot:
  name: Standup Octopus
  emoji: ':octopus:'
  channel: standups
  # channel: standups-test
# users that participate in the standup
users:
  - edisonywh
  - nirvanagoh
  - bam.chiamsie
  - atinder.bhinder
  - fionkohz
  - kevinlee
  - alwychristyo

standup:
  # Time for the standup to commence in 24hour format, leading 0 required
  time: 010:30
  # days to perform standup 1 = Mon 5 = Fri
  days:
    - 1
    - 2
    - 3
    - 4
    - 5

# debug: true
